//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemshkanPR1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Creator
    {
        public int CreatorID { get; set; }
        public string CreatorName { get; set; }
    }
}
