//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemshkanPR1
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Windows.Media.Imaging;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderProduct = new HashSet<OrderProduct>();
        }
    
        public string ProductArticleNumber { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public int ProductCategory { get; set; }
        public string ProductPhoto { get; set; }
        public int ProductManufacturer { get; set; }
        public decimal ProductCost { get; set; }
        public Nullable<byte> ProductDiscountAmount { get; set; }
        public int ProductQuantityInStock { get; set; }
        public int ProductTransfer { get; set; }
        public byte PoductMaxDiscount { get; set; }
        public int PoductUnitMeasurement { get; set; }
        public BitmapImage ImageCopy
        {
            get
            {
                if (ProductPhoto != null)
                {
                    BitmapImage bi = new BitmapImage();
                    MemoryStream bytestream = new MemoryStream(File.ReadAllBytes(ProductPhoto));
                    bi.BeginInit();
                    bi.DecodePixelWidth = 100;
                    bi.StreamSource = bytestream;
                    bi.EndInit();
                    return bi;
                }
                else return null;
            }
        }
        public virtual Manufacturer Manufacturer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProduct> OrderProduct { get; set; }
        public virtual Transfer Transfer { get; set; }
        public virtual TypePorduct TypePorduct { get; set; }
        public virtual UnitMeasurement UnitMeasurement { get; set; }
    }
}
